public class OpcodeInfo {
    public static String getMnemonic(int opcode) {
        opcode &= 0xFF;
        switch (opcode) {
            case 0x00: return "NOP";
            case 0x01: return "LD BC,d16";
            case 0x02: return "LD (BC),A";
            case 0x03: return "INC BC";
            case 0x04: return "INC B";
            case 0x05: return "DEC B";
            case 0x06: return "LD B,d8";
            case 0x07: return "RLCA";
            case 0x08: return "LD (a16),SP";
            case 0x09: return "ADD HL,BC";
            case 0x0A: return "LD A,(BC)";
            case 0x0B: return "DEC BC";
            case 0x0C: return "INC C";
            case 0x0D: return "DEC C";
            case 0x0E: return "LD C,d8";
            case 0x0F: return "RRCA";
            case 0x10: return "STOP 0";
            case 0x11: return "LD DE,d16";
            case 0x12: return "LD (DE),A";
            case 0x13: return "INC DE";
            case 0x14: return "INC D";
            case 0x15: return "DEC D";
            case 0x16: return "LD D,d8";
            case 0x17: return "RLA";
            case 0x18: return "JR r8";
            case 0x19: return "ADD HL,DE";
            case 0x1A: return "LD A,(DE)";
            case 0x1B: return "DEC DE";
            case 0x1C: return "INC E";
            case 0x1D: return "DEC E";
            case 0x1E: return "LD E,d8";
            case 0x1F: return "RRA";
            case 0x20: return "JR NZ,r8";
            case 0x21: return "LD HL,d16";
            case 0x22: return "LD (HL+),A";
            case 0x23: return "INC HL";
            case 0x24: return "INC H";
            case 0x25: return "DEC H";
            case 0x26: return "LD H,d8";
            case 0x27: return "DAA";
            case 0x28: return "JR Z,r8";
            case 0x29: return "ADD HL,HL";
            case 0x2A: return "LD A,(HL+)";
            case 0x2B: return "DEC HL";
            case 0x2C: return "INC L";
            case 0x2D: return "DEC L";
            case 0x2E: return "LD L,d8";
            case 0x2F: return "CPL";
            case 0x30: return "JR NC,r8";
            case 0x31: return "LD SP,d16";
            case 0x32: return "LD (HL-),A";
            case 0x33: return "INC SP";
            case 0x34: return "INC (HL)";
            case 0x35: return "DEC (HL)";
            case 0x36: return "LD (HL),d8";
            case 0x37: return "SCF";
            case 0x38: return "JR C,r8";
            case 0x39: return "ADD HL,SP";
            case 0x3A: return "LD A,(HL-)";
            case 0x3B: return "DEC SP";
            case 0x3C: return "INC A";
            case 0x3D: return "DEC A";
            case 0x3E: return "LD A,d8";
            case 0x3F: return "CCF";
            case 0x40: return "UNDEFINED_40";
            case 0x41: return "UNDEFINED_41";
            case 0x42: return "UNDEFINED_42";
            case 0x43: return "UNDEFINED_43";
            case 0x44: return "UNDEFINED_44";
            case 0x45: return "UNDEFINED_45";
            case 0x46: return "UNDEFINED_46";
            case 0x47: return "UNDEFINED_47";
            case 0x48: return "UNDEFINED_48";
            case 0x49: return "UNDEFINED_49";
            case 0x4A: return "UNDEFINED_4A";
            case 0x4B: return "UNDEFINED_4B";
            case 0x4C: return "UNDEFINED_4C";
            case 0x4D: return "UNDEFINED_4D";
            case 0x4E: return "UNDEFINED_4E";
            case 0x4F: return "UNDEFINED_4F";
            case 0x50: return "UNDEFINED_50";
            case 0x51: return "UNDEFINED_51";
            case 0x52: return "UNDEFINED_52";
            case 0x53: return "UNDEFINED_53";
            case 0x54: return "UNDEFINED_54";
            case 0x55: return "UNDEFINED_55";
            case 0x56: return "UNDEFINED_56";
            case 0x57: return "UNDEFINED_57";
            case 0x58: return "UNDEFINED_58";
            case 0x59: return "UNDEFINED_59";
            case 0x5A: return "UNDEFINED_5A";
            case 0x5B: return "UNDEFINED_5B";
            case 0x5C: return "UNDEFINED_5C";
            case 0x5D: return "UNDEFINED_5D";
            case 0x5E: return "UNDEFINED_5E";
            case 0x5F: return "UNDEFINED_5F";
            case 0x60: return "UNDEFINED_60";
            case 0x61: return "UNDEFINED_61";
            case 0x62: return "UNDEFINED_62";
            case 0x63: return "UNDEFINED_63";
            case 0x64: return "UNDEFINED_64";
            case 0x65: return "UNDEFINED_65";
            case 0x66: return "UNDEFINED_66";
            case 0x67: return "UNDEFINED_67";
            case 0x68: return "UNDEFINED_68";
            case 0x69: return "UNDEFINED_69";
            case 0x6A: return "UNDEFINED_6A";
            case 0x6B: return "UNDEFINED_6B";
            case 0x6C: return "UNDEFINED_6C";
            case 0x6D: return "UNDEFINED_6D";
            case 0x6E: return "UNDEFINED_6E";
            case 0x6F: return "UNDEFINED_6F";
            case 0x70: return "UNDEFINED_70";
            case 0x71: return "UNDEFINED_71";
            case 0x72: return "UNDEFINED_72";
            case 0x73: return "UNDEFINED_73";
            case 0x74: return "UNDEFINED_74";
            case 0x75: return "UNDEFINED_75";
            case 0x76: return "HALT";
            case 0x77: return "UNDEFINED_77";
            case 0x78: return "UNDEFINED_78";
            case 0x79: return "UNDEFINED_79";
            case 0x7A: return "UNDEFINED_7A";
            case 0x7B: return "UNDEFINED_7B";
            case 0x7C: return "UNDEFINED_7C";
            case 0x7D: return "UNDEFINED_7D";
            case 0x7E: return "UNDEFINED_7E";
            case 0x7F: return "UNDEFINED_7F";
            case 0x80: return "UNDEFINED_80";
            case 0x81: return "UNDEFINED_81";
            case 0x82: return "UNDEFINED_82";
            case 0x83: return "UNDEFINED_83";
            case 0x84: return "UNDEFINED_84";
            case 0x85: return "UNDEFINED_85";
            case 0x86: return "UNDEFINED_86";
            case 0x87: return "UNDEFINED_87";
            case 0x88: return "UNDEFINED_88";
            case 0x89: return "UNDEFINED_89";
            case 0x8A: return "UNDEFINED_8A";
            case 0x8B: return "UNDEFINED_8B";
            case 0x8C: return "UNDEFINED_8C";
            case 0x8D: return "UNDEFINED_8D";
            case 0x8E: return "UNDEFINED_8E";
            case 0x8F: return "UNDEFINED_8F";
            case 0x90: return "UNDEFINED_90";
            case 0x91: return "UNDEFINED_91";
            case 0x92: return "UNDEFINED_92";
            case 0x93: return "UNDEFINED_93";
            case 0x94: return "UNDEFINED_94";
            case 0x95: return "UNDEFINED_95";
            case 0x96: return "UNDEFINED_96";
            case 0x97: return "UNDEFINED_97";
            case 0x98: return "UNDEFINED_98";
            case 0x99: return "UNDEFINED_99";
            case 0x9A: return "UNDEFINED_9A";
            case 0x9B: return "UNDEFINED_9B";
            case 0x9C: return "UNDEFINED_9C";
            case 0x9D: return "UNDEFINED_9D";
            case 0x9E: return "UNDEFINED_9E";
            case 0x9F: return "UNDEFINED_9F";
            case 0xA0: return "UNDEFINED_A0";
            case 0xA1: return "UNDEFINED_A1";
            case 0xA2: return "UNDEFINED_A2";
            case 0xA3: return "UNDEFINED_A3";
            case 0xA4: return "UNDEFINED_A4";
            case 0xA5: return "UNDEFINED_A5";
            case 0xA6: return "UNDEFINED_A6";
            case 0xA7: return "UNDEFINED_A7";
            case 0xA8: return "UNDEFINED_A8";
            case 0xA9: return "UNDEFINED_A9";
            case 0xAA: return "UNDEFINED_AA";
            case 0xAB: return "UNDEFINED_AB";
            case 0xAC: return "UNDEFINED_AC";
            case 0xAD: return "UNDEFINED_AD";
            case 0xAE: return "UNDEFINED_AE";
            case 0xAF: return "XOR A";
            case 0xB0: return "UNDEFINED_B0";
            case 0xB1: return "UNDEFINED_B1";
            case 0xB2: return "UNDEFINED_B2";
            case 0xB3: return "UNDEFINED_B3";
            case 0xB4: return "UNDEFINED_B4";
            case 0xB5: return "UNDEFINED_B5";
            case 0xB6: return "UNDEFINED_B6";
            case 0xB7: return "UNDEFINED_B7";
            case 0xB8: return "UNDEFINED_B8";
            case 0xB9: return "UNDEFINED_B9";
            case 0xBA: return "UNDEFINED_BA";
            case 0xBB: return "UNDEFINED_BB";
            case 0xBC: return "UNDEFINED_BC";
            case 0xBD: return "UNDEFINED_BD";
            case 0xBE: return "UNDEFINED_BE";
            case 0xBF: return "UNDEFINED_BF";
            case 0xC0: return "UNDEFINED_C0";
            case 0xC1: return "UNDEFINED_C1";
            case 0xC2: return "UNDEFINED_C2";
            case 0xC3: return "JP a16";
            case 0xC4: return "UNDEFINED_C4";
            case 0xC5: return "UNDEFINED_C5";
            case 0xC6: return "ADD A,d8";
            case 0xC7: return "UNDEFINED_C7";
            case 0xC8: return "UNDEFINED_C8";
            case 0xC9: return "RET";
            case 0xCA: return "UNDEFINED_CA";
            case 0xCB: return "UNDEFINED_CB";
            case 0xCC: return "UNDEFINED_CC";
            case 0xCD: return "CALL a16";
            case 0xCE: return "ADC A,d8";
            case 0xCF: return "UNDEFINED_CF";
            case 0xD0: return "UNDEFINED_D0";
            case 0xD1: return "UNDEFINED_D1";
            case 0xD2: return "UNDEFINED_D2";
            case 0xD3: return "UNDEFINED_D3";
            case 0xD4: return "UNDEFINED_D4";
            case 0xD5: return "UNDEFINED_D5";
            case 0xD6: return "UNDEFINED_D6";
            case 0xD7: return "UNDEFINED_D7";
            case 0xD8: return "UNDEFINED_D8";
            case 0xD9: return "UNDEFINED_D9";
            case 0xDA: return "UNDEFINED_DA";
            case 0xDB: return "UNDEFINED_DB";
            case 0xDC: return "UNDEFINED_DC";
            case 0xDD: return "UNDEFINED_DD";
            case 0xDE: return "UNDEFINED_DE";
            case 0xDF: return "UNDEFINED_DF";
            case 0xE0: return "LDH (a8),A";
            case 0xE1: return "UNDEFINED_E1";
            case 0xE2: return "LD (C),A";
            case 0xE3: return "UNDEFINED_E3";
            case 0xE4: return "UNDEFINED_E4";
            case 0xE5: return "UNDEFINED_E5";
            case 0xE6: return "UNDEFINED_E6";
            case 0xE7: return "UNDEFINED_E7";
            case 0xE8: return "UNDEFINED_E8";
            case 0xE9: return "UNDEFINED_E9";
            case 0xEA: return "LD (a16),A";
            case 0xEB: return "UNDEFINED_EB";
            case 0xEC: return "UNDEFINED_EC";
            case 0xED: return "UNDEFINED_ED";
            case 0xEE: return "UNDEFINED_EE";
            case 0xEF: return "UNDEFINED_EF";
            case 0xF0: return "LDH A,(a8)";
            case 0xF1: return "UNDEFINED_F1";
            case 0xF2: return "UNDEFINED_F2";
            case 0xF3: return "DI";
            case 0xF4: return "UNDEFINED_F4";
            case 0xF5: return "UNDEFINED_F5";
            case 0xF6: return "UNDEFINED_F6";
            case 0xF7: return "UNDEFINED_F7";
            case 0xF8: return "UNDEFINED_F8";
            case 0xF9: return "UNDEFINED_F9";
            case 0xFA: return "UNDEFINED_FA";
            case 0xFB: return "EI";
            case 0xFC: return "UNDEFINED_FC";
            case 0xFD: return "UNDEFINED_FD";
            case 0xFE: return "CP d8";
            case 0xFF: return "UNDEFINED_FF";
            default: return String.format("UNDEFINED_%02X", opcode);
        }
    }

    public static int getInstructionLength(int opcode) {
        opcode &= 0xFF;
        switch (opcode) {
            case 0x00: return 1;
            case 0x01: return 3;
            case 0x02: return 1;
            case 0x03: return 1;
            case 0x04: return 1;
            case 0x05: return 1;
            case 0x06: return 2;
            case 0x07: return 1;
            case 0x08: return 3;
            case 0x09: return 1;
            case 0x0A: return 1;
            case 0x0B: return 1;
            case 0x0C: return 1;
            case 0x0D: return 1;
            case 0x0E: return 2;
            case 0x0F: return 1;
            case 0x10: return 2;
            case 0x11: return 3;
            case 0x12: return 1;
            case 0x13: return 1;
            case 0x14: return 1;
            case 0x15: return 1;
            case 0x16: return 2;
            case 0x17: return 1;
            case 0x18: return 2;
            case 0x19: return 1;
            case 0x1A: return 1;
            case 0x1B: return 1;
            case 0x1C: return 1;
            case 0x1D: return 1;
            case 0x1E: return 2;
            case 0x1F: return 1;
            case 0x20: return 2;
            case 0x21: return 3;
            case 0x22: return 1;
            case 0x23: return 1;
            case 0x24: return 1;
            case 0x25: return 1;
            case 0x26: return 2;
            case 0x27: return 1;
            case 0x28: return 2;
            case 0x29: return 1;
            case 0x2A: return 1;
            case 0x2B: return 1;
            case 0x2C: return 1;
            case 0x2D: return 1;
            case 0x2E: return 2;
            case 0x2F: return 1;
            case 0x30: return 2;
            case 0x31: return 3;
            case 0x32: return 1;
            case 0x33: return 1;
            case 0x34: return 1;
            case 0x35: return 1;
            case 0x36: return 2;
            case 0x37: return 1;
            case 0x38: return 2;
            case 0x39: return 1;
            case 0x3A: return 1;
            case 0x3B: return 1;
            case 0x3C: return 1;
            case 0x3D: return 1;
            case 0x3E: return 2;
            case 0x3F: return 1;
            case 0x40: return 1;
            case 0x41: return 1;
            case 0x42: return 1;
            case 0x43: return 1;
            case 0x44: return 1;
            case 0x45: return 1;
            case 0x46: return 1;
            case 0x47: return 1;
            case 0x48: return 1;
            case 0x49: return 1;
            case 0x4A: return 1;
            case 0x4B: return 1;
            case 0x4C: return 1;
            case 0x4D: return 1;
            case 0x4E: return 1;
            case 0x4F: return 1;
            case 0x50: return 1;
            case 0x51: return 1;
            case 0x52: return 1;
            case 0x53: return 1;
            case 0x54: return 1;
            case 0x55: return 1;
            case 0x56: return 1;
            case 0x57: return 1;
            case 0x58: return 1;
            case 0x59: return 1;
            case 0x5A: return 1;
            case 0x5B: return 1;
            case 0x5C: return 1;
            case 0x5D: return 1;
            case 0x5E: return 1;
            case 0x5F: return 1;
            case 0x60: return 1;
            case 0x61: return 1;
            case 0x62: return 1;
            case 0x63: return 1;
            case 0x64: return 1;
            case 0x65: return 1;
            case 0x66: return 1;
            case 0x67: return 1;
            case 0x68: return 1;
            case 0x69: return 1;
            case 0x6A: return 1;
            case 0x6B: return 1;
            case 0x6C: return 1;
            case 0x6D: return 1;
            case 0x6E: return 1;
            case 0x6F: return 1;
            case 0x70: return 1;
            case 0x71: return 1;
            case 0x72: return 1;
            case 0x73: return 1;
            case 0x74: return 1;
            case 0x75: return 1;
            case 0x76: return 1;
            case 0x77: return 1;
            case 0x78: return 1;
            case 0x79: return 1;
            case 0x7A: return 1;
            case 0x7B: return 1;
            case 0x7C: return 1;
            case 0x7D: return 1;
            case 0x7E: return 1;
            case 0x7F: return 1;
            case 0x80: return 1;
            case 0x81: return 1;
            case 0x82: return 1;
            case 0x83: return 1;
            case 0x84: return 1;
            case 0x85: return 1;
            case 0x86: return 1;
            case 0x87: return 1;
            case 0x88: return 1;
            case 0x89: return 1;
            case 0x8A: return 1;
            case 0x8B: return 1;
            case 0x8C: return 1;
            case 0x8D: return 1;
            case 0x8E: return 1;
            case 0x8F: return 1;
            case 0x90: return 1;
            case 0x91: return 1;
            case 0x92: return 1;
            case 0x93: return 1;
            case 0x94: return 1;
            case 0x95: return 1;
            case 0x96: return 1;
            case 0x97: return 1;
            case 0x98: return 1;
            case 0x99: return 1;
            case 0x9A: return 1;
            case 0x9B: return 1;
            case 0x9C: return 1;
            case 0x9D: return 1;
            case 0x9E: return 1;
            case 0x9F: return 1;
            case 0xA0: return 1;
            case 0xA1: return 1;
            case 0xA2: return 1;
            case 0xA3: return 1;
            case 0xA4: return 1;
            case 0xA5: return 1;
            case 0xA6: return 1;
            case 0xA7: return 1;
            case 0xA8: return 1;
            case 0xA9: return 1;
            case 0xAA: return 1;
            case 0xAB: return 1;
            case 0xAC: return 1;
            case 0xAD: return 1;
            case 0xAE: return 1;
            case 0xAF: return 1;
            case 0xB0: return 1;
            case 0xB1: return 1;
            case 0xB2: return 1;
            case 0xB3: return 1;
            case 0xB4: return 1;
            case 0xB5: return 1;
            case 0xB6: return 1;
            case 0xB7: return 1;
            case 0xB8: return 1;
            case 0xB9: return 1;
            case 0xBA: return 1;
            case 0xBB: return 1;
            case 0xBC: return 1;
            case 0xBD: return 1;
            case 0xBE: return 1;
            case 0xBF: return 1;
            case 0xC0: return 1;
            case 0xC1: return 1;
            case 0xC2: return 1;
            case 0xC3: return 3;
            case 0xC4: return 1;
            case 0xC5: return 1;
            case 0xC6: return 2;
            case 0xC7: return 1;
            case 0xC8: return 1;
            case 0xC9: return 1;
            case 0xCA: return 1;
            case 0xCB: return 1;
            case 0xCC: return 1;
            case 0xCD: return 3;
            case 0xCE: return 2;
            case 0xCF: return 1;
            case 0xD0: return 1;
            case 0xD1: return 1;
            case 0xD2: return 1;
            case 0xD3: return 1;
            case 0xD4: return 1;
            case 0xD5: return 1;
            case 0xD6: return 1;
            case 0xD7: return 1;
            case 0xD8: return 1;
            case 0xD9: return 1;
            case 0xDA: return 1;
            case 0xDB: return 1;
            case 0xDC: return 1;
            case 0xDD: return 1;
            case 0xDE: return 1;
            case 0xDF: return 1;
            case 0xE0: return 2;
            case 0xE1: return 1;
            case 0xE2: return 1;
            case 0xE3: return 1;
            case 0xE4: return 1;
            case 0xE5: return 1;
            case 0xE6: return 1;
            case 0xE7: return 1;
            case 0xE8: return 1;
            case 0xE9: return 1;
            case 0xEA: return 3;
            case 0xEB: return 1;
            case 0xEC: return 1;
            case 0xED: return 1;
            case 0xEE: return 1;
            case 0xEF: return 1;
            case 0xF0: return 2;
            case 0xF1: return 1;
            case 0xF2: return 1;
            case 0xF3: return 1;
            case 0xF4: return 1;
            case 0xF5: return 1;
            case 0xF6: return 1;
            case 0xF7: return 1;
            case 0xF8: return 1;
            case 0xF9: return 1;
            case 0xFA: return 1;
            case 0xFB: return 1;
            case 0xFC: return 1;
            case 0xFD: return 1;
            case 0xFE: return 2;
            case 0xFF: return 1;
            default: return 1;
        }
    }
}